FROM node:21-alpine3.18

WORKDIR /app
COPY package.json ./
COPY tsconfig.json ./
COPY dist ./dist
COPY src ./src
COPY private_key.pem /app/private_key.pem

RUN ls -a
RUN npm install && npm install -g nodemon

EXPOSE 4000

CMD [ "npm", "run", "start:dev" ]